import Head from "next/head";
import { getSession } from "next-auth/client";

import Header from "../components/header/Header";
import Login from "../components/login/Login";
import Sidebar from "../components/sidebar/Sidebar";
import Feed from "./../components/feed/Feed";

export default function Home({ session }) {
  if (!session) return <Login />;

  return (
    <div>
      <Head>
        <title>Facebook Clone</title>
        <meta
          name="description"
          content="Fb Clone generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header user={session.user} />

      <main className="flex bg-gray-100">
        <Sidebar />
        <Feed />
        <Sidebar />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  //get the user
  const session = await getSession(context);
  return {
    props: {
      session,
    },
  };
}
