import Head from "next/head";
import { useState } from "react";

import Header from "../components/header/Header";
import Login from "../components/login/Login";
import Sidebar from "../components/sidebar/Sidebar";
import Feed from "./../components/feed/Feed";

export default function Home() {
  const [user, setUser] = useState(null);

  const signOut = () => {
    auth.signOut().then(() => {
      setUser(null);
    });
  };

  return (
    <div>
      {!user ? (
        <Login setUser={setUser} />
      ) : (
        <div>
          <Head>
            <title>Facebook Clone</title>
            <meta
              name="description"
              content="Fb Clone generated by create next app"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <Header user={user} />

          <main className="flex bg-gray-100">
            <Sidebar user={user} />
            <Feed user={user} />
            <Sidebar user={user} />
          </main>
        </div>
      )}
    </div>
  );
}
